# ?????????????????????????????????????????
# BIDIWS ? Profil DEV
# ?????????????????????????????????????????
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
logging.level.com.bidiws=DEBUG
logging.level.org.hibernate.SQL=DEBUG