# ?????????????????????????????????????????
# BIDIWS ? Profil PROD
# ?????????????????????????????????????????
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate
logging.level.com.bidiws=INFO
logging.level.org.springframework.security=WARN